/* 
Approach 2: Event-based IO.
So, Each Client request can be completed in multiple iterations() -> There is a need for processing state management. We defines the state in Connection object.
Connection {
    ...
    incoming: accumulates the data copied from TCP kernel buffer.
    outgoing: stores data that is generated by the server and hasn't been sent to the client.
}
- Using Pollfd is a way interact with kernel, ask kernel to monitor multiple fd for readiness.
    Pollfd {
    ... 
    fd: the socket that being monitored.
    events: What action (Read/ Write/ Both) is required for that pollfd which associated to a specific soket.
    revents = returned events: what the pollfd kernel actually found (can read/ can write/ or both). - Kernel modifies this automatically.
    }
- At each iteration (while(true)){
    Do a non-blocking read.
    Add new Data to non-blocking buffer.
    Try to parse the accumulated buffer (connection.incoming) -> if not enough data -> do nothing in that iteration.
    Process the parsed message.
    Remove the parsed message from connection.incoming
}
*/

#include <iostream>
#include <cerrno>

#include <sys/socket.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <poll.h>
#include <fcntl.h>

#include "utils.hpp"
#include "socket.hpp"
#include <assert.h>


namespace {
    const int kPort = 1234;
    const int kBacklog = SOMAXCONN;
    const size_t kReadBufferSize = 64*1024;
    const std::size_t kMaxMessageSize = 4096;
    const size_t kHeaderSize = 4;
    
    class Connection {
    public:
        explicit Connection(Socket socket) : socket{std::move(socket)} {}
        Socket socket;
        bool wantRead{true};
        bool wantWrite{false};
        bool wantClose{false};
        std::vector<uint8_t> incoming;
        std::vector<uint8_t> outgoing;
    };
    void setNonBlocking(int fd) {
        /* 
        Check current status of the File Descriptor.
        fcntl = File Control.
        Non-Blocking flag determines the behaviours of the socket.
        - Blocking Socket: if read() -> kernel buffer is empty -> thread sleeps -> wait for network -> data arrives -> read() & return
        - Non-Blocking socket: Read() -> empty kernel buffer -> return immediately -> errno = EAGAIN.
        */
        const int flags = fcntl(fd, F_GETFL, 0);
        if (flags < 0) {
            throwSystemError("fcntl(F_GETFL)");
        }

        if (fcntl(fd, F_SETFL, flags | O_NONBLOCK) < 0) { // Set flags = current flags + O_NONBLOCK flag.
            throwSystemError("fcntl(F_SETFL)");
        }
    }
    Socket createSocketServer() {
        Socket serverSocket{socket(AF_INET, SOCK_STREAM, 0)}; // Instantiate serverSocket with IPv4 protocol, and TCP type.
        if (!serverSocket.valid()) throwSystemError("Socket()");

        int enabled = 1;
        if  (setsockopt(serverSocket.get(),
                SOL_SOCKET,
                SO_REUSEADDR,
                &enabled,
                sizeof(enabled)) < 0
            ) {
                throwSystemError("setsockopt");
            }
        // Configure Socket address
        sockaddr_in serverAddress{};
        serverAddress.sin_family = AF_INET;
        serverAddress.sin_port = htons(kPort);
        serverAddress.sin_addr.s_addr = htonl(INADDR_ANY);
        
        if (bind(
            serverSocket.get(),
            reinterpret_cast<const sockaddr*>(&serverAddress),
            sizeof(serverAddress)
            ) < 0) 
            {
                throwSystemError("bind()");
            }
        
        setNonBlocking(serverSocket.get());
        if (::listen(serverSocket.get(), kBacklog) < 0) throwSystemError("listen()");
    
        return serverSocket;
    }

    std::unique_ptr<Connection> handleAccept(int listenFd) {
        sockaddr_in clientAddress{};
        socklen_t clientAddressLength = sizeof(clientAddress);

        const int connectionFd = accept(
            listenFd,
            reinterpret_cast<sockaddr*>(&clientAddress),
            &clientAddressLength
        );

        if (connectionFd < 0) {
            if (errno != EAGAIN && errno != EWOULDBLOCK) {
            logMessage("accept() failed");
            }
            return nullptr;
        }
        setNonBlocking(connectionFd);
        // Convert Binary IP to human readable IP - Eg: C0 A8 01 14 -> 192.168.1.20
        char ipAddress[INET_ADDRSTRLEN]{};
        inet_ntop( 
            AF_INET,
            &clientAddress.sin_addr,
            ipAddress,
            sizeof(ipAddress)
        );
        std::cout << "New client from "
              << ipAddress
              << ':'
              << ntohs(clientAddress.sin_port)
              << '\n';

        return std::make_unique<Connection>(Socket{connectionFd});
    }
    
    void appendBuffer(
        std::vector<uint8_t>& buffer,
        const uint8_t* data,
        std::size_t length
    ) {
        buffer.insert(buffer.end(), data, data + length);
    }

    void consumeBuffer(std::vector<uint8_t>& buffer, std::size_t length) {
        assert(length <= buffer.size());
        buffer.erase(buffer.begin(), buffer.begin() + static_cast<std::ptrdiff_t>(length));
    }
    
    bool handleOneRequest(Connection& connection) {
        if(connection.incoming.size() < kHeaderSize) return false; // Incoming only contains partial Header data.
        
        // Extract messageLength from header
        uint32_t rawMessageLength = 0; // raw header bytes Eg: 00 00 00 05
        std::memcpy(
            &rawMessageLength,
            connection.incoming.data(),
            kHeaderSize
        );

        const uint32_t messageLength = ntohl(rawMessageLength);

        if (messageLength > kMaxMessageSize) {
            logMessage("Message too long");
            connection.wantClose = true;
            return false;
        }

        const std::size_t fullMessageSize = kHeaderSize + messageLength;

        if (connection.incoming.size() < fullMessageSize) return false; // Not Enough message, wait for more data from read()
        
        const uint8_t* messageBodyBegin = connection.incoming.data() + kHeaderSize; // pointer to the first char of message body
        std::string_view message{
            reinterpret_cast<const char*>(messageBodyBegin),
            messageLength
        };
        std::cout << "Client says: " << message.substr(0, 100) << '\n';

        /* Generate Response */
        const std::string prefix = "Server Acknowledge the message: ";
        std::string response = prefix + std::string{
            reinterpret_cast<const char*>(messageBodyBegin),
            messageLength
        };
        const uint32_t responseLength = static_cast<uint32_t>(response.size());
        const uint32_t networkResponseLength = htonl(responseLength);

        // Append header
        appendBuffer(   
            connection.outgoing,
            reinterpret_cast<const uint8_t*>(&networkResponseLength), 
            kHeaderSize
        );
        // append response
        appendBuffer(
            connection.outgoing,
            reinterpret_cast<const uint8_t*>(response.data()),
            response.size()
        );

        consumeBuffer(connection.incoming, fullMessageSize);

        return true;
    }
    void handleWrite(Connection& connection) {
        if (connection.outgoing.empty()) {
            connection.wantWrite = false;
            connection.wantRead = true;
            return;
        }

        const ssize_t bytesWritten = write(
            connection.socket.get(),
            connection.outgoing.data(),
            connection.outgoing.size()
        );

        if (bytesWritten < 0) {
            if (errno == EAGAIN || errno == EWOULDBLOCK) {
                return;
            }

            logMessage("write() failed");
            connection.wantClose = true;
            return;
        }

        consumeBuffer(
            connection.outgoing,
            static_cast<std::size_t>(bytesWritten)
        );

        if (connection.outgoing.empty()) {
            connection.wantRead = true;
            connection.wantWrite = false;
        }
    }

    void handleRead(Connection& connection) {
        std::array<uint8_t, kReadBufferSize> buffer{};
        const ssize_t bytesRead = read(
            connection.socket.get(),
            buffer.data(),
            buffer.size()
        );
        
        if(bytesRead < 0) {
            if (errno == EAGAIN || errno == EWOULDBLOCK) {
            return;
            }

            logMessage("read() failed");
            connection.wantClose = true;
            return;
        }

        if (bytesRead == 0) {
            if (connection.incoming.empty()) {
                std::cerr << "Client closed connection\n";
            } else {
                std::cerr << "Unexpected EOF\n";
            }

            connection.wantClose = true;
            return;
        }

        appendBuffer(
            connection.incoming,
            buffer.data(),
            bytesRead
        ); // append all the client's messages sent to the connection socket to the connection.incoming - byte stream of different messages now.

        while(handleOneRequest(connection)) {} // continuously process the messages until can't process anymore.
        
        if (!connection.outgoing.empty()) {
        connection.wantRead = false;
        connection.wantWrite = true;
        // After done reading, assuming the write kernel is not full -> write the response immediately without waiting for the next iteration.
        handleWrite(connection);
    }
    }

    
    
}



int main() {
    Socket listenSocket = createSocketServer();
    std::cout << "Server Listening on port: " << kPort << std::endl;
    /* 
    a vector (use heap memory -> dynamically allocation and is scalable as runtime) of socket. using type smart pointer which owns a connection object for automatically executing "delete" later.
    */
    std::vector<std::unique_ptr<Connection>> fd2conn; 
    std::vector<pollfd> pollFds{}; // a list of polls. each poll watches one socket.

    while(true) {
        pollFds.clear();
        // add the listening (server) socket to the poll. set events for watching to POLLIN (read).
        pollFds.push_back(pollfd{
            .fd = listenSocket.get(),
            .events = POLLIN,
            .revents = 0    
        });
        
        for (const auto& connection : fd2conn) { // you need to use actual value of connection, not a copy version -> type + & is required. auto type let compiler automatically setting the type of object (Eg: when extracts connection from the list or when connection is terminated -> type = )
            if (!connection) continue;

            short events = POLLERR; // socket error
            if (connection->wantRead) {
                events |= POLLIN; // there are data waiting to read for the current socket in kernel receive buffer.
            }
            if (connection->wantWrite) {
                events |= POLLOUT; // There is more space to write in kernel send buffer.
            }
            // append the connection socket to poll vector.
            pollFds.push_back(pollfd{
                .fd = connection -> socket.get(),
                .events = events,
                .revents = 0
            });
        }
        const int readyCount = poll(
            pollFds.data(), 
            static_cast<nfds_t>(pollFds.size()),
            -1 // time out 
        );
        if(readyCount < 0) {
            if(errno == EINTR){
                continue;
            }
            throwSystemError("poll()");
        }
        /* Working on the Listening Socket */
        if (pollFds[0].revents & POLLIN) { // bit manipulation.
            // There might be more than 1 client requests sent to server at a time, Everytime handleAccept() is executed, one request will be pulled out from the stack by accept() to be processed. Loop until no more request -> return null.
            while(auto connection = handleAccept(listenSocket.get())) { // a temporary connection variable.
                const int connectionFd = connection->socket.get();

                if(fd2conn.size() <= connectionFd) {
                    fd2conn.resize(connectionFd + 1);   
                }

                assert(!fd2conn[connectionFd]);
                fd2conn[connectionFd] = std::move(connection); // Move the ownership of connection to Fd2conn connection socket index.
            }
        }
        for (std::size_t i = 1; i < pollFds.size(); ++i) // Process connection sockets
        {
            const int fd = pollFds[i].fd;
            const short ready = pollFds[i].revents;

            if (ready == 0) continue;

            assert(ready > 0);
            assert(static_cast<std::size_t>(fd) < fd2conn.size());

            Connection* connection = fd2conn[fd].get();
            if(!connection) continue;

            // handle read
            if (ready & POLLIN) {
                assert(connection->wantRead);
                handleRead(*connection);
            }
            // Handle wrire
            if (ready & POLLOUT) {
                assert(connection->wantWrite);
                handleWrite(*connection);
            }
            // Close the socket from socket error or application logic
            if ((ready & POLLERR) || connection->wantClose) {
                std::cout << "Client disconnected\n";
                fd2conn[fd].reset();
            }
        }
        
    }
    
    return 0;
}